[package]
name = "trustek_contracts"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.8.2"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
build = "scarb build"
test = "scarb test"
